import { readFile, writeFile } from 'node:fs/promises';
import ts from 'typescript';
import { escape } from '../design-system/layout.ts';

// An offline design review, deliberately separate from the publication bundle.
const root = new URL('../', import.meta.url);
const source = await readFile(new URL('index.html', root), 'utf8');
const styles = source.match(/<style>([\s\S]*?)<\/style>/)![1];
const collection = source.match(/<main id="main" class="collection-page">[\s\S]*?<\/main>/)![0]
  .replaceAll('id="main"', 'id="sample-main"')
  .replace(/href="[^"]*"/g, 'href="#" tabindex="-1"');
const brand = source.match(/<a class="brand"[^>]*>([\s\S]*?)<\/a>/)![1];
// Reuse A's actual rules, colors, timing and geometry, rather than approximating it.
const optionA = [...styles.matchAll(/body\[data-page='collection'\]\[data-ambient='A'\]::(?:before|after) \{[^}]+\}/g)]
  .map(([rule]) => rule.replace(/body\[data-page='collection'\]\[data-ambient='A'\]/, '.lab-effect[data-effect="A"]'))
  .join('\n');
if (!optionA) throw new Error('The preserved Option A styles could not be found.');
const studies = [
  { id: 'A', name: 'Contour drift', kind: 'The reference', note: 'The one you liked. Fine topographic lines travel over quiet fields of color.', detail: 'The original, unchanged. Two contour systems drift against one another; the broad color fields move more slowly underneath.', cue: 'Follow an intersection between two contour lines.', engine: 'CSS · original treatment' },
  { id: 'B', name: 'Silk current', kind: 'Woven / fluid', note: 'Hundreds of fine threads turn, fold and slip past each other like suspended silk.', detail: 'Two translucent ribbons fold in three dimensions. Individual threads become visible at the edges, then gather into luminous seams as the fabric turns.', cue: 'Watch the narrow fold open into a wide ribbon.', engine: 'Canvas · parametric ribbons' },
  { id: 'C', name: 'Waterlight', kind: 'Refracted / organic', note: 'The shifting lace of sunlight on the floor of a very still pool.', detail: 'An evolving refractive field creates soft cells and concentrated veins of light. No particles or waves are drawn; the pattern is the light itself.', cue: 'Watch the small cells join, stretch and separate.', engine: 'Canvas · procedural caustics' },
  { id: 'D', name: 'Orbital ink', kind: 'Sculptural / precise', note: 'An impossible wire sculpture, slowly turning in the space behind the page.', detail: 'Fine copper and teal loops form a three-dimensional torus. As it rotates, the open center closes into a woven edge and opens again.', cue: 'Follow the central opening as the sculpture turns.', engine: 'Canvas · projected geometry' },
  { id: 'E', name: 'Paper eclipse', kind: 'Tactile / architectural', note: 'Cut-paper discs pass over each other, revealing slivers of light and shadow.', detail: 'Layered, nearly monochrome circles cast soft shadows. Their slow relative motion changes the negative space, like an architectural model under moving daylight.', cue: 'Watch the crescent-shaped spaces between the discs.', engine: 'Canvas · layered light and shadow' },
  { id: 'F', name: 'Murmuration', kind: 'Generative / alive', note: 'A thousand small marks gather into a shape that never quite settles.', detail: 'A deterministic particle field folds around invisible attractors. The marks stay individually quiet; their collective movement creates the image.', cue: 'Step back and watch the whole silhouette breathe.', engine: 'Canvas · coordinated particle field' },
];
const css = await readFile(new URL('backgrounds.css', import.meta.url), 'utf8');
const uiSource = (await Promise.all(['design-system/murmuration.ts', 'previews/backgrounds-ui.ts'].map(path => readFile(new URL(path, root), 'utf8')))).join('\n');
const ui = ts.transpileModule(uiSource, { compilerOptions: { target: ts.ScriptTarget.ES2023, module: ts.ModuleKind.None } }).outputText;
const cards = studies.map(study => `<button class="lab-card" type="button" data-open-study="${study.id}" aria-label="Preview ${study.id}: ${study.name}">
  <span class="lab-art"><span class="lab-effect" data-effect="${study.id}" aria-hidden="true"><canvas></canvas></span><span class="lab-card-index">${study.id}</span>${study.id === 'A' ? '<span class="lab-reference">Preserved original</span>' : ''}<span class="lab-open">View full screen <span aria-hidden="true">↗</span></span></span>
  <span class="lab-card-meta"><span class="lab-kind">${study.kind}</span><span class="lab-card-title">${study.name}</span><span class="lab-card-note">${study.note}</span></span>
</button>`).join('\n');
const themeControls = `<div class="lab-segment" role="group" aria-label="Preview theme"><button type="button" data-lab-theme="light" aria-pressed="true">Light</button><button type="button" data-lab-theme="dark" aria-pressed="false">Dark</button></div>`;
const html = `<!doctype html>
<!-- Generated by npm run preview:backgrounds. Sources: previews/build-backgrounds.ts, backgrounds.css, backgrounds-ui.ts. -->
<html lang="en" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Six moving atmospheres · The Way I AI</title>
<style>${styles}\n${optionA}\n${css}</style></head><body class="lab-body">
<main class="lab-gallery">
  <header class="lab-top"><span class="lab-signature">The Way I AI <span>/ motion studies</span></span><div class="lab-tools">${themeControls}<button class="lab-button" type="button" data-lab-pause aria-pressed="false">Pause motion</button></div></header>
  <section class="lab-intro"><div><p class="lab-kicker">Atmosphere, not decoration · 06 studies</p><h1>Something quietly<br><em>alive.</em></h1></div><div class="lab-intro-note"><p>Six different ways to make a still page move. Not six palettes of the same idea.</p><p>Open one to see it behind the actual site. Give it a few seconds; the movement is part of the composition.</p></div></section>
  <section class="lab-grid" aria-label="Six animated background studies">${cards}</section>
  <footer class="lab-footer"><span>A is preserved. F at 20% intensity is the selected homepage treatment; the other studies stay here for comparison.</span><span data-motion-note>All effects run locally. No video, libraries or network.</span></footer>
</main>
<dialog class="lab-viewer" aria-labelledby="lab-viewer-title">
  <div class="lab-viewer-bar"><button class="lab-button" type="button" data-lab-close>← All six <span class="lab-key">Esc</span></button><div class="lab-study-heading"><span id="lab-viewer-id">A</span><h2 id="lab-viewer-title">Contour drift</h2></div><div class="lab-tools">${themeControls}<button class="lab-button" type="button" data-lab-pause aria-pressed="false">Pause motion</button></div></div>
  <div class="lab-stage" tabindex="0" aria-label="Full-screen background preview">
    <div id="lab-stage-effect" class="lab-effect" data-effect="A" aria-hidden="true"><canvas></canvas></div>
    <div class="lab-site" data-lab-content><div class="site-shell"><div class="lab-sitebar"><span class="brand">${brand}</span><span>Collection preview · links disabled</span></div>${collection}</div></div>
    <div class="lab-background-caption" hidden><span>Background study</span><strong>Contour drift</strong></div>
  </div>
  <div class="lab-dock"><div class="lab-description"><p id="lab-detail"></p><span id="lab-cue"></span></div><div class="lab-adjust"><button type="button" class="lab-button" data-lab-content-toggle aria-pressed="false">Background only</button><label class="lab-strength">Intensity <input id="lab-strength" type="range" min="20" max="100" value="65"><output for="lab-strength">65%</output></label></div><nav class="lab-choices" aria-label="Choose background">${studies.map(study => `<button type="button" data-lab-choice="${study.id}" aria-label="${study.id}: ${escape(study.name)}" aria-pressed="false">${study.id}</button>`).join('')}</nav></div>
</dialog>
<script type="application/json" id="lab-studies">${JSON.stringify(studies).replaceAll('<', '\\u003c')}</script>
<script>${ui.replaceAll('</script', '<\\/script')}</script>
</body></html>\n`;
await writeFile(new URL('backgrounds.html', import.meta.url), html);
console.log('Built previews/backgrounds.html — open directly in a browser (fully offline).');
