import type { Collection, RenderedTopic, RenderedDocument, ShellOptions } from './types.ts';
export const escape = (value: unknown) => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));

// GitHub mark from Primer Octicons; license retained in design-system/licenses.
const githubMark = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M6.766 11.328c-2.063-.25-3.516-1.734-3.516-3.656 0-.781.281-1.625.75-2.188-.203-.515-.172-1.609.063-2.062.625-.078 1.468.25 1.968.703.594-.187 1.219-.281 1.985-.281.765 0 1.39.094 1.953.265.484-.437 1.344-.765 1.969-.687.218.422.25 1.515.046 2.047.5.593.766 1.39.766 2.203 0 1.922-1.453 3.375-3.547 3.64.531.344.89 1.094.89 1.954v1.625c0 .468.391.734.86.547C13.781 14.359 16 11.53 16 8.03 16 3.61 12.406 0 7.984 0 3.563 0 0 3.61 0 8.031a7.88 7.88 0 0 0 5.172 7.422c.422.156.828-.125.828-.547v-1.25c-.219.094-.5.156-.75.156-1.031 0-1.64-.562-2.078-1.609-.172-.422-.36-.672-.719-.719-.187-.015-.25-.093-.25-.187 0-.188.313-.328.625-.328.453 0 .844.281 1.25.86.313.452.64.655 1.031.655s.641-.14 1-.5c.266-.265.47-.5.657-.656"/></svg>';
const icon = (content: string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${content}</svg>`;
const icons = {
  sidebar: icon('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16m4-11 3 3-3 3"/>'),
  light: icon('<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.4 1.4m11.2 11.2L19 19M5 19l1.4-1.4M17.6 6.4L19 5"/>'),
  dark: icon('<path d="M20 14.5A8.5 8.5 0 0 1 9.5 4 8.5 8.5 0 1 0 20 14.5Z"/>'),
  system: icon('<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>'),
  search: icon('<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>'),
};
function themePicker() {
  return `<details class="theme-picker js-only"><summary class="icon-button" aria-label="Color theme: System. Choose a theme" title="Color theme: System">${Object.entries(icons).filter(([key]) => ['light', 'dark', 'system'].includes(key)).map(([key, svg]) => `<span class="theme-current theme-${key}">${svg}</span>`).join('')}</summary><div class="theme-options" role="group" aria-label="Color theme">${(['light', 'dark', 'system'] as const).map(choice => `<button type="button" class="icon-button" data-theme-choice="${choice}" aria-label="${choice[0].toUpperCase() + choice.slice(1)} theme" title="${choice === 'system' ? 'Follow system theme' : `${choice[0].toUpperCase() + choice.slice(1)} theme`}" aria-pressed="${choice === 'system'}">${icons[choice]}</button>`).join('')}</div></details>`;
}
export function shell({ title, description, body, css, js, themeJS, search, fonts, collection, prefix = '', page = 'collection', wordmarkBackground = false }: ShellOptions) {
  const searchJSON = JSON.stringify(search.map(entry => ({ ...entry, href: prefix + entry.href }))).replaceAll('<', '\\u003c');
  return `<!doctype html>
<!-- Generated by npm run build. Edit Markdown and design-system sources. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escape(description)}"><meta name="color-scheme" content="light dark"><title>${escape(title)} · ${escape(collection.title)}</title>
<script>${themeJS.replaceAll('</script', '<\\/script')}</script><style>${fonts}\n${css}</style>
</head><body data-page="${escape(page)}"><a class="skip-link" href="#main">Skip to content</a>
<div class="site-shell"><header class="masthead"><a class="brand" href="${prefix}index.html" aria-label="${escape(collection.title)} — home"><span class="wordmark" aria-hidden="true">${wordmarkContent(collection, wordmarkBackground)}</span></a><button type="button" class="search-trigger js-only" data-open-search aria-haspopup="dialog" aria-label="Search the collection">${icons.search}<span>Search the collection</span><kbd aria-hidden="true">⌘ K</kbd></button><div class="header-actions">${themePicker()}${collection.repositoryUrl ? `<a class="repo-link" href="${escape(collection.repositoryUrl)}" target="_blank" rel="noopener noreferrer" aria-label="View the repository on GitHub (opens in a new tab)" title="View on GitHub">${githubMark}</a>` : ''}</div></header>
${body}
<footer class="footer"><span class="brand-name">${escape(collection.title)}</span><a href="#main">Back to top ↑</a></footer></div>
<dialog class="search-dialog" aria-labelledby="search-title"><div class="dialog-head"><h2 id="search-title">Search the collection</h2><button type="button" class="small-button" data-close-search aria-label="Close search">Esc</button></div><label class="sr-only" for="collection-search">Search ideas and full text</label><input id="collection-search" type="search" placeholder="Search ideas and full text…" autocomplete="off"><p class="search-result-status" role="status"></p><div class="search-results"></div></dialog>
<div class="toast" role="status" hidden></div><script type="application/json" id="collection-search-data">${searchJSON}</script><script>${js.replaceAll('</script', '<\\/script')}</script></body></html>\n`;
}

function wordmarkContent(collection: Collection, withBackground: boolean) {
  const titleLines = collection.displayTitle.split('\n');
  const displayTitle = titleLines.map((line, index) => {
    const text = escape(line);
    const [initial = '', ...rest] = [...line];
    const content = index === 0
      ? text.replace(/^(\S+)(\s+)/, '<span class="title-prefix">$1</span>$2')
      : index === titleLines.length - 1
        ? `<span class="title-initial">${escape(initial)}</span>${escape(rest.join(''))}`
        : text;
    return `<span class="title-line">${content}</span>`;
  }).join('');
  return `${withBackground ? '<span class="title-art" aria-hidden="true"></span>' : ''}${displayTitle}`;
}

export function collectionBody(topics: RenderedTopic[], collection: Collection, withBackground = false) {
  const [statement, ...intro] = (collection.introduction[0] ?? '').split('\n');
  return `<main id="main" class="collection-page"><section class="collection-hero"><div class="hero-wordmark"><h1 class="wordmark" aria-label="${escape(collection.displayTitle.split('\n').join(' '))}">${wordmarkContent(collection, withBackground)}</h1></div><div class="collection-intro"><h2>${escape(statement)}</h2>${[...intro, ...collection.introduction.slice(1)].map(paragraph => `<p>${escape(paragraph).replaceAll('\n', '<br>')}</p>`).join('')}<a class="text-link" href="#topics-heading">Explore the collection <span aria-hidden="true">↗</span></a></div></section>
  <section aria-labelledby="topics-heading"><div class="section-label"><h2 id="topics-heading">The reading list</h2><span>${topics.length} ${topics.length === 1 ? 'topic' : 'topics'}</span></div><div class="topic-grid">${topics.map(topic => `<a class="topic-card" href="topics/${topic.id}/index.html" aria-labelledby="topic-${topic.id}-title"><div class="topic-visual${topic.coverSVG ? '' : ' no-cover'}"><span class="card-number">${escape(topic.number)}</span>${topic.coverSVG || ''}</div><div class="topic-copy"><div class="card-meta"><span class="eyebrow">${escape(topic.category)}</span><span>${topic.minutes} min read</span></div><h3 id="topic-${topic.id}-title">${escape(topic.title)}</h3><p>${escape(topic.description)}</p><span class="text-link">Read the topic <span aria-hidden="true">↗</span></span></div></a>`).join('')}</div></section></main>`;
}

export function readerBody(topic: RenderedTopic, topics: RenderedTopic[], documents: RenderedDocument[], explorer: string) {
  const currentIndex = topics.findIndex(item => item.id === topic.id);
  const next = topics[(currentIndex + 1) % topics.length];
  const outline = `<aside class="on-page" aria-label="Section navigation"><details class="contents" open><summary>On this page</summary><div class="contents-inner"><span class="contents-label">On this page</span><div class="search-wrap js-only"><label class="sr-only" for="section-search">Find a section by heading or content</label><input id="section-search" type="search" placeholder="Find a section…" autocomplete="off"><kbd aria-hidden="true">/</kbd></div><p class="search-status js-only" data-search-status aria-live="polite">Search headings and full text</p><nav aria-label="On this page">${documents.map(doc => `<div class="toc-document"><p class="toc-group">${escape(doc.label)}</p><ol class="toc-list">${doc.headings.map(heading => `<li data-subsection="${heading.level > 2}"><a class="toc-link ${heading.level > 2 ? 'subsection' : ''}" href="#${heading.id}">${escape(heading.text)}</a></li>`).join('')}</ol></div>`).join('')}</nav></div></details></aside>`;
  return `<div class="workspace"><aside class="collection-nav" aria-label="Collection navigation"><details class="collection-contents"><summary aria-label="Expand collection sidebar" title="Expand collection sidebar">${icons.sidebar}<span>The collection</span></summary><nav aria-label="Topics"><a class="nav-home" href="../../index.html">The collection</a>${topics.map(item => `<a class="nav-topic" href="../${item.id}/index.html" ${item.id === topic.id ? 'aria-current="page"' : ''}><span class="nav-number">${escape(item.number)}</span><span>${escape(item.title)}</span></a>`).join('')}</nav></details></aside>
  <main id="main" class="reading-layout">${outline}<div class="reading-main"><div class="breadcrumbs"><a href="../../index.html">The collection</a><span aria-hidden="true">/</span><span>${escape(topic.category)}</span></div><header class="topic-hero"><h1>${escape(topic.title)}</h1><p class="lead">${escape(topic.description)}</p><div class="hero-meta"><span>${topic.minutes} min read</span></div></header><div class="reader-tools js-only"><button type="button" data-focus aria-pressed="false">Focus on reading</button><button type="button" data-print>Print / save PDF ↗</button></div>
  ${explorer ? `<details class="visual-guide"><summary>Explore the idea visually <span aria-hidden="true">↗</span></summary>${explorer}</details>` : ''}
  <article class="article" aria-label="Complete topic text">${documents.map(doc => `<section class="source-document" aria-labelledby="${doc.id}-title"><header class="source-heading"><div class="eyebrow">${escape(doc.label)}</div><h2 class="source-title" id="${doc.id}-title">${escape(doc.title)}</h2></header><div class="prose" data-source="${escape(doc.file)}">${doc.html}</div></section>`).join('')}
  ${next && next.id !== topic.id ? `<section class="next-topic"><span class="eyebrow">Next topic / ${escape(next.number)}</span><h2><a href="../${next.id}/index.html">${escape(next.title)} ↗</a></h2><p>${escape(next.thesis)}</p></section>` : ''}</article></div>
  </main></div>`;
}
