import type { Collection, RenderedTopic, RenderedDocument, ShellOptions } from './types.ts';
export const escape = (value: unknown) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));

// GitHub mark from Primer Octicons; license retained in design-system/licenses.
const githubMark = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M6.766 11.328c-2.063-.25-3.516-1.734-3.516-3.656 0-.781.281-1.625.75-2.188-.203-.515-.172-1.609.063-2.062.625-.078 1.468.25 1.968.703.594-.187 1.219-.281 1.985-.281.765 0 1.39.094 1.953.265.484-.437 1.344-.765 1.969-.687.218.422.25 1.515.046 2.047.5.593.766 1.39.766 2.203 0 1.922-1.453 3.375-3.547 3.64.531.344.89 1.094.89 1.954v1.625c0 .468.391.734.86.547C13.781 14.359 16 11.53 16 8.03 16 3.61 12.406 0 7.984 0 3.563 0 0 3.61 0 8.031a7.88 7.88 0 0 0 5.172 7.422c.422.156.828-.125.828-.547v-1.25c-.219.094-.5.156-.75.156-1.031 0-1.64-.562-2.078-1.609-.172-.422-.36-.672-.719-.719-.187-.015-.25-.093-.25-.187 0-.188.313-.328.625-.328.453 0 .844.281 1.25.86.313.452.64.655 1.031.655s.641-.14 1-.5c.266-.265.47-.5.657-.656\"/></svg>";

export function shell({ title, description, body, css, js, fonts, collection, prefix = '', page = 'collection', wordmarkBackground = false }: ShellOptions) {
  return `<!doctype html>
<!-- Generated by npm run build. Edit Markdown and design-system sources. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escape(description)}"><meta name="color-scheme" content="light dark"><title>${escape(title)} · ${escape(collection.title)}</title>
<style>${fonts}\n${css}</style>
<script>document.documentElement.classList.add('js');try{const t=localStorage.getItem('the-way-i-ai-theme');if(t==='dark'||t==='light')document.documentElement.dataset.theme=t;else if(matchMedia('(prefers-color-scheme: dark)').matches)document.documentElement.dataset.theme='dark'}catch{}</script>
</head><body data-page="${page}"><a class="skip-link" href="#main">Skip to content</a>
<div class="page-width"><header class="masthead"><a class="brand" href="${prefix}index.html" aria-label="${escape(collection.title)} — home"><span class="wordmark" aria-hidden="true">${wordmarkContent(collection, wordmarkBackground)}</span></a><nav aria-label="Collection"><a href="${prefix}index.html">Contents</a><button class="small-button js-only" data-theme-toggle aria-label="Switch color theme">Dark mode</button><button class="small-button print-button js-only" data-print>Print</button></nav>${collection.repositoryUrl ? `<a class="repo-link" href="${escape(collection.repositoryUrl)}" target="_blank" rel="noopener noreferrer" aria-label="View the repository on GitHub (opens in a new tab)" title="View on GitHub">${githubMark}</a>` : ''}</header>
${body}
<footer class="footer"><span><span class="brand-name">${escape(collection.title)}</span> <span aria-hidden="true">/</span> ${escape(collection.subtitle)}</span><a href="${prefix}index.html">Contents</a></footer></div>
<a class="small-button back-top js-only" href="#main" aria-label="Back to top">↑ Top</a><div class="toast" role="status" hidden></div>
<script>${js.replaceAll('</script', '<\\/script')}</script></body></html>\n`;
}

function wordmarkContent(collection: Collection, withBackground: boolean) {
  const titleLines = collection.displayTitle.split('\n');
  const displayTitle = titleLines.map((line, index) => {
    const text = escape(line);
    const [initial = '', ...rest] = [...line];
    const content = index === 0
      ? text.replace(/^(\S+)(\s+)/, '<span class="title-prefix">$1</span>$2')
      : index === titleLines.length - 1
        ? `<span class="title-initial">${escape(initial)}</span>${escape(rest.join(''))}`
        : text;
    return `<span class="title-line">${content}</span>`;
  }).join('');
  return `${withBackground ? '<span class="title-art" aria-hidden="true"></span>' : ''}${displayTitle}`;
}

export function collectionBody(topics: RenderedTopic[], collection: Collection, withBackground = false) {
  return `<main id="main"><div class="edition-line eyebrow"><span>${escape(collection.eyebrow)}</span></div>
  <section class="collection-hero"><h1 class="wordmark" aria-label="${escape(collection.displayTitle.split('\n').join(' '))}">${wordmarkContent(collection, withBackground)}</h1><div class="collection-intro">${collection.introduction.map(paragraph => `<p>${escape(paragraph).replaceAll('\n', '<br>')}</p>`).join('')}</div></section>
  <section aria-labelledby="topics-heading"><div class="section-label"><h2 id="topics-heading">Explore the collection</h2></div>
  <div class="topic-grid">${topics.map(topic => `<a class="topic-card" href="topics/${topic.id}/index.html" aria-labelledby="topic-${topic.id}-title"><div class="topic-visual${topic.coverSVG ? '' : ' no-cover'}"><span class="card-number">${escape(topic.number)}</span>${topic.coverSVG || ''}</div><div class="topic-copy"><span class="eyebrow">${escape(topic.category)}</span><h3 id="topic-${topic.id}-title">${escape(topic.title)}</h3><p>${escape(topic.description)}</p><div class="card-links"><span class="text-link">Explore the idea <span aria-hidden="true">↗</span></span><span>${topic.minutes} min read · ${topic.documents.length === 1 ? 'Essay' : 'Guide + tools'}</span></div></div></a>`).join('')}</div></section>
  </main>`;
}

export function readerBody(topic: RenderedTopic, topics: RenderedTopic[], documents: RenderedDocument[], explorer: string) {
  const currentIndex = topics.findIndex(item => item.id === topic.id);
  const next = topics[(currentIndex + 1) % topics.length];
  return `<main id="main"><div class="edition-line eyebrow"><a href="../../index.html">The collection</a><span class="rule"></span><span>Topic ${escape(topic.number)} / ${escape(topic.category)}</span></div>
    <header class="topic-hero"><h1>${escape(topic.title)}</h1><p class="lead">${escape(topic.description)}</p><div class="hero-meta"><span>${topic.minutes} min read</span><span>Complete text + visual guide</span></div></header>
    ${explorer}
    <div class="reader-layout"><aside aria-label="Section navigation"><details class="contents" open><summary>Contents &amp; search</summary><div class="contents-inner"><span class="eyebrow">In this topic</span><div class="search-wrap js-only"><label class="sr-only" for="section-search">Find a section by heading or content</label><input id="section-search" type="search" placeholder="Find a section…" autocomplete="off"><kbd aria-hidden="true">/</kbd></div><p class="search-status js-only" data-search-status aria-live="polite">Search headings and full text</p><nav aria-label="On this page">${documents.map(doc => `<div class="toc-document"><p class="toc-group">${escape(doc.label)}</p><ol class="toc-list">${doc.headings.map(heading => `<li data-subsection="${heading.level > 2}"><a class="toc-link ${heading.level > 2 ? 'subsection' : ''}" href="#${heading.id}">${escape(heading.text)}</a></li>`).join('')}</ol></div>`).join('')}</nav><div class="reading-status js-only"><span>Reading progress</span><span data-progress-text>0%</span></div><div class="reading-track" aria-hidden="true"><span data-progress></span></div></div></details></aside>
    <article class="article" aria-label="Complete topic text">${documents.map(doc => `<section class="source-document" aria-labelledby="${doc.id}-title"><header class="source-heading"><div class="eyebrow"><span>${escape(doc.label)} / Full text</span></div><h2 class="source-title" id="${doc.id}-title">${escape(doc.title)}</h2></header><div class="prose" data-source="${escape(doc.file)}">${doc.html}</div></section>`).join('')}
    ${next && next.id !== topic.id ? `<section class="next-topic"><span class="eyebrow">Continue the collection / ${escape(next.number)}</span><h2><a href="../${next.id}/index.html">${escape(next.title)} ↗</a></h2><p>${escape(next.thesis)}</p></section>` : ''}</article></div></main>`;
}
